[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["display"] }
regex = "1.11.1"
strum = { version = "0.26.3", features = ["derive"] }
